
import "./globals.css";
import { Rancho } from "next/font/google";
import { AuthProvider } from "@/context/AuthContext";
const rancho = Rancho({ subsets: ["latin"], weight: ["400"] });
import NavbarLayout from "@/components/NavbarLayout";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={rancho.className}>
        <AuthProvider>
          <NavbarLayout>
            {children}
          </NavbarLayout>
        </AuthProvider>

      </body>
    </html>
  );
}
