import "./globals.css";
import { Rancho } from "next/font/google";
import Header from "../components/Header";
const rancho = Rancho({ subsets: ["latin"], weight: ["400"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={rancho.className}>
        
        {children}
      </body>
    </html>
  );
}
